<?php
/**
 * 
 * View -- of Hr/EmployeeController/addfamilyAction
 * 
 */
$this->headTitle($this->title);
?>

<form id="#form" method="post" action="<?php echo $this->url('employee', array('action' => 'addfamily', 'id' => $this->id)); ?>"  enctype="multipart/form-data" >    
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->  
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
			<div class="form-group">
					<label for="cid" class="control-label">CID</label>
					<input type="text" class="form-control" name="cid" id="cid" required /> 
				</div>
				<div class="form-group">
					<label for="name" class="control-label">Name</label>
					<input type="text" class="form-control" name="name" id="name" required /> 
				</div>
				<div class="form-group">
					<label for="name_dzo" class="control-label uchen">མིང་</label>
					<input type="text" class="form-control" name="name_dzo" id="name_dzo" required /> 
				</div>
				<div class="form-group">
					<label for="institute" class="control-label">Relation</label>
					<input type="text" class="form-control" name="relation" id="relation" required /> 
				</div>
				<div class="form-group">
					<label for="nationality" class="control-label">Nationality</label>
					<input type="text" class="form-control" name="nationality" id="nationality" required /> 
				</div>
				<div class="form-group">
					<label for="occupation" class="control-label">Occupation</label>
					<input type="text" class="form-control" name="occupation" id="occupation" required /> 
				</div>
				<div class="form-group">
					<label for="contact" class="control-label">Contact</label>
					<input type="text" class="form-control" name="contact" id="contact" required /> 
				</div>
				<div class="form-group">
					<label for="address" class="control-label">Address</label>
					<input type="text" class="form-control" name="address" id="address" required /> 
				</div>
				<div class="form-group">
					<label for="remarks" class="control-label">Remarks</label>
					<input type="text" class="form-control" name="remarks" id="remarks" /> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form> 
<script>
$('document').ready(function(){
	$('#cid').on('change', function(){
		$.post(
			"<?php echo $this->url('employee', array('action' => 'getciddtl')); ?>",
			{
				cid: $(this).val(),
			},
			function(data){
			console.log(data); 
			$('#cid').val(data.cid);
			$('#name').val(data.name);
			$('#occupation').val(data.occupation);
			$('#name_dzo').val(data.name_dzo);
			$('#father_name').val(data.fatherName);
			$('#mother_name').val(data.motherName);
			$('input#dob').val(data.dob);
			$('#gender').val(data.gender);
			$('#thram_no').val(data.thram_no);
			$('#house_no').val(data.house_no);
			$('#dzongkhags').val(data.dzongkhag);
			$('#gewog').val(data.gewog);
			$('#village').val(data.village);
			if(data.dob == ''){ $('#message1').html(data.message);	}
			},
			'json'
		);
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			name: {
				validators: {
					notEmpty: {
						message: 'Please provide name.'
					}
				}
			},
			relation: {
				validators: {
					notEmpty: {
						message: 'Please provide relation.'
					}
				}
			},
			nationality: {
				validators: {
					notEmpty: {
						message: 'Please provide nationality.'
					}
				}
			},
			occupation: {
				validators: {
					notEmpty: {
						message: 'Please provide occupation.'
					}
				}
			},
			address: {
				validators: {
					notEmpty: {
						message: 'Please provide address.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>  
