<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<main>
    <section class="home" id="home">
        <div class="container">
            <div class="home__inner">
                <div class="home__items">
                    <h1 class="home__title">
                        Athang <br />
                        is waiting for you
                    </h1>
                    <p class="home__subtitle text">
                        is a pioneering software development and trainingacademy firm greatly driven
                        by the information technology. The company was founded in 2005 with the aim
                        to meet the ever changing demand of the customers in the field of ICT.
                        Athang strives for the excellence in offering our services, be it a training
                        programme or developing your website or producing an animation work that our
                        audience would love to watch or restoring your internet breakdown and many
                        more… As a company, Athang believes in the team work and democratic working
                        culture to bring the best of every employees at personal as well as
                        professional level.
                    </p>
                    <a href="https://www.athang.com/public/w" class="home__link btn">Know more</a>
                </div>
                    <div class="home__image">
                        <img src="https://www.athang.com/public/images/logo.jpg" alt="home img" class="home__img img">
                    </div>
            </div>
        </div>
    </section>

</main>

                <!-- start of video.php -->
                <main>
                    <section class="tv-series">
                        <div class="container">
                            <p class="section-subtitle">Best Series</p>
                            <h2 class="h2 section-title">Athang Series</h2>
                            <ul class="movies-list">

                                <li>
                                    <div class="movie-card">

                                        <a href="https://www.youtube.com/watch?v=5NSr6MgDsRA&t=4s">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">Ap Bokto</h3>
                                            </a>

                                            <time datetime="2022">2022</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">2K</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT122M">122 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>7.8</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="https://www.youtube.com/watch?v=F80B1GCxzgI">
                                            <figure class="card-banner">
                                                <img src="https://pbs.twimg.com/profile_images/652434380279840768/hfOScPdq_400x400.jpg"
                                                    alt="Morbius movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">Ap bokto lite</h3>
                                            </a>

                                            <time datetime="2022">2022</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">HD</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT104M">104 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>5.9</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="./movie-details.html">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">The Adam Project</h3>
                                            </a>

                                            <time datetime="2022">2022</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">4K</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT106M">106 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>7.0</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="./movie-details.html">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">Free Guy</h3>
                                            </a>

                                            <time datetime="2021">2021</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">4K</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT115M">115 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>7.7</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="./movie-details.html">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">The Batman</h3>
                                            </a>

                                            <time datetime="2022">2022</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">4K</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT176M">176 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>7.9</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="./movie-details.html">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">Uncharted</h3>
                                            </a>

                                            <time datetime="2022">2022</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">HD</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT116M">116 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>7.0</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="./movie-details.html">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">Death on the Nile</h3>
                                            </a>

                                            <time datetime="2022">2022</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">2K</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT127M">127 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>6.5</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <div class="movie-card">

                                        <a href="./movie-details.html">
                                            <figure class="card-banner">
                                                <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/Ap_Bokto.jpg"
                                                    alt="Sonic the Hedgehog 2 movie poster">
                                            </figure>
                                        </a>

                                        <div class="title-wrapper">
                                            <a href="./movie-details.html">
                                                <h3 class="card-title">The King's Man</h3>
                                            </a>

                                            <time datetime="2021">2021</time>
                                        </div>

                                        <div class="card-meta">
                                            <div class="badge badge-outline">HD</div>

                                            <div class="duration">
                                                <ion-icon name="time-outline"></ion-icon>

                                                <time datetime="PT131M">131 min</time>
                                            </div>

                                            <div class="rating">
                                                <ion-icon name="star"></ion-icon>

                                                <data>7.0</data>
                                            </div>
                                        </div>

                                    </div>
                                </li>

                            </ul>

                        </div>
                    </section>



                    <section class="tv-series">
                        <div class="container">

                            <p class="section-subtitle">Best shorts</p>

                            <h2 class="h2 section-title">Athang Series</h2>

                            <ul class="movies-list">
                                @foreach ($students as $shorts)
                                    <li>

                                        <div class="movie-card">

                                            <a href="{{ $shorts->vediolink }}">
                                                <figure class="card-banner">
                                                    <img src="{{ $shorts->image }}" alt="Moon Knight movie poster">
                                                </figure>
                                            </a>

                                            <div class="title-wrapper">
                                                <a href="./movie-details.html">
                                                    <h3 class="card-title">{{ $shorts->name }}</h3>
                                                </a>

                                                <time datetime="2022">2023</time>
                                            </div>

                                            <div class="card-meta">
                                                <div class="badge badge-outline">#{{ $loop->iteration }}Trending</div>

                                                <div class="duration">
                                                    <ion-icon name="time-outline"></ion-icon>

                                                    <time datetime="PT47M">47 min</time>
                                                </div>

                                                <div class="rating">
                                                    <ion-icon name="star"></ion-icon>

                                                    <data>8.6</data>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                @endforeach
                            </ul>

                        </div>
                    </section>
                </main>




