<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico',
    ])
        ->prependStylesheet($this->basePath('css/all.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-icons.css'))
        ->prependStylesheet($this->basePath('css/styles.min.css'))
        ?>

    <?= $this->headLink([
        'rel' => 'stylesheet',
        'href' => 'https://fonts.googleapis.com/icon?family=Material+Icons',
    ]) ?>
    <?= $this->headLink([
        'rel' => 'stylesheet',
        'href' => 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css',
        'integrity' => 'sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ',
        'crossorigin' => 'anonymous',
    ]) ?>


    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>


<body>

    <!-- <div class="container"> -->


    <div id="wrapper">

        <div id="anime-trending">
            <div class="container">
                <section class="block_area block_area_trending">
                    <div class="block_area-header">
                        <div class="bah-heading">
                            <h2 class="cat-heading">Athang Shorts</h2>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="block_area-content">
                        <div class="trending-list" id="trending-home" style="display: none;">
                            <div class="swiper-container">
                                <div class="swiper-wrapper">
                                    <!-- @foreach ($students as $shorts) -->
                                    <div class="swiper-slide item-qtip" data-id="100">

                                        <div class="item">
                                            <div class="number">
                                                <span>hi</span>
                                                <div class="film-title dynamic-name" data-jname="">

                                                    hi
                                                </div>
                                            </div>
                                            <a href="hi" class="film-poster">
                                                <img data-src="hi" class="film-poster-img lazyload" title="hi" alt="">
                                            </a>
                                            <div class="clearfix"></div>
                                        </div>

                                    </div>
                                    <!-- @endforeach -->

                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="trending-navi">
                                <div class="navi-next"><i class="bi bi-arrow-right-circle"></i></div>
                                <div class="navi-prev"><i class="fas fa-angle-left"></i></div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>


        <!--/End: trending-->
        <div class="share-buttons share-buttons-home">
            <div class="container">
                <div class="share-buttons-block">
                    <div class="share-icon"></div>
                    <div class="sbb-title">
                        <span color="black !important">Share Athang Shorts</span>
                        <p class="mb-0">to your friends</p>
                    </div>
                    <div class="addthis_inline_share_toolbox"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!--Begin: Events-->



        <section class="block_area block_area_home">
            <div class="block_area-header">
                <div class="float-left bah-heading mr-4">
                    <h2 class="cat-heading">Ap Bokto Seriess</h2>
                </div>
                <div class="float-right viewmore"><a class="btn" href="/recently-updated">View more<i
                            class="fas fa-angle-right ml-2"></i></a></div>
                <div class="clearfix"></div>
            </div>
            <div class="tab-content">
                <div class="block_area-content block_area-list film_list film_list-grid">
                    <div class="film_list-wrap">

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>9
                                    </div>



                                    <div class="tick-item tick-eps">12</div>

                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/aa/c8/aac8106ff0d4a84f7b44e8f78582aa38/aac8106ff0d4a84f7b44e8f78582aa38.png"
                                    class="film-poster-img lazyload" alt="Painting Rivers and Lakes 6">
                                <a href="/painting-rivers-and-lakes-6-18266" class="film-poster-ahref item-qtip"
                                    title="Painting Rivers and Lakes 6" data-id="18266"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/painting-rivers-and-lakes-6-18266"
                                        title="Painting Rivers and Lakes 6" class="dynamic-name"
                                        data-jname="Hua Jianghu: Bu Liang Ren VI">Painting Rivers and Lakes
                                        6</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">ONA</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">26m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>4
                                    </div>



                                    <div class="tick-item tick-eps">12</div>

                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/ef/58/ef589599341efbee4e87edd81f6648ae/ef589599341efbee4e87edd81f6648ae.jpg"
                                    class="film-poster-img lazyload" alt="Kizuna no Allele">
                                <a href="/kizuna-no-allele-18370" class="film-poster-ahref item-qtip"
                                    title="Kizuna no Allele" data-id="18370"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/kizuna-no-allele-18370" title="Kizuna no Allele"
                                        class="dynamic-name" data-jname="Kizuna no Allele">Kizuna no Allele</a>
                                </h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>4
                                    </div>


                                    <div class="tick-item tick-dub"><i class="fas fa-microphone mr-1"></i>1
                                    </div>


                                    <div class="tick-item tick-eps">13</div>

                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/0a/d5/0ad5356f28ee75bccfde8b69ea6a5e54/0ad5356f28ee75bccfde8b69ea6a5e54.jpg"
                                    class="film-poster-img lazyload"
                                    alt="I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too">
                                <a href="/i-got-a-cheat-skill-in-another-world-and-became-unrivaled-in-the-real-world-too-18343"
                                    class="film-poster-ahref item-qtip"
                                    title="I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too"
                                    data-id="18343"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a
                                        href="/i-got-a-cheat-skill-in-another-world-and-became-unrivaled-in-the-real-world-too-18343"
                                        title="I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too"
                                        class="dynamic-name"
                                        data-jname="Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu Sekai wo mo Musou Suru: Level Up wa Jinsei wo Kaeta">I
                                        Got a Cheat Skill in Another World and Became Unrivaled in The Real
                                        World, Too</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">24m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">

                                <div class="tick tick-rate">18+</div>


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>16
                                    </div>


                                    <div class="tick-item tick-dub"><i class="fas fa-microphone mr-1"></i>14
                                    </div>


                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/17/3e/173e4c5db060f057506138057261b259/173e4c5db060f057506138057261b259.jpg"
                                    class="film-poster-img lazyload" alt="Vinland Saga: 2nd Season">
                                <a href="/vinland-saga-2nd-season-18239" class="film-poster-ahref item-qtip"
                                    title="Vinland Saga: 2nd Season" data-id="18239"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/vinland-saga-2nd-season-18239"
                                        title="Vinland Saga: 2nd Season" class="dynamic-name"
                                        data-jname="Vinland Saga Season 2">Vinland Saga: 2nd Season</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>3
                                    </div>



                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/20/2a/202a4c434af567174dc7683de096a96c/202a4c434af567174dc7683de096a96c.jpg"
                                    class="film-poster-img lazyload" alt="Insomniacs After School">
                                <a href="/insomniacs-after-school-18344" class="film-poster-ahref item-qtip"
                                    title="Insomniacs After School" data-id="18344"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/insomniacs-after-school-18344"
                                        title="Insomniacs After School" class="dynamic-name"
                                        data-jname="Kimi wa Houkago Insomnia">Insomniacs After School</a>
                                </h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>4
                                    </div>


                                    <div class="tick-item tick-dub"><i class="fas fa-microphone mr-1"></i>2
                                    </div>


                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/ba/cb/bacb7124d070a26097c77601250a205e/bacb7124d070a26097c77601250a205e.jpg"
                                    class="film-poster-img lazyload" alt="In Another World With My Smartphone 2">
                                <a href="/in-another-world-with-my-smartphone-2-18342"
                                    class="film-poster-ahref item-qtip" title="In Another World With My Smartphone 2"
                                    data-id="18342"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/in-another-world-with-my-smartphone-2-18342"
                                        title="In Another World With My Smartphone 2" class="dynamic-name"
                                        data-jname="Isekai wa Smartphone to Tomo ni. 2">In Another World
                                        With My Smartphone 2</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>3
                                    </div>


                                    <div class="tick-item tick-dub"><i class="fas fa-microphone mr-1"></i>1
                                    </div>


                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/3a/06/3a06250cf428b5e830f2fee15b96f1a4/3a06250cf428b5e830f2fee15b96f1a4.jpg"
                                    class="film-poster-img lazyload" alt="Dead Mount Death Play">
                                <a href="/dead-mount-death-play-18352" class="film-poster-ahref item-qtip"
                                    title="Dead Mount Death Play" data-id="18352"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/dead-mount-death-play-18352"
                                        title="Dead Mount Death Play" class="dynamic-name"
                                        data-jname="Dead Mount Death Play">Dead Mount Death Play</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>4
                                    </div>



                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/90/a1/90a1dbcb03b97c209fd2b3e8fdeee1af/90a1dbcb03b97c209fd2b3e8fdeee1af.jpg"
                                    class="film-poster-img lazyload" alt="Alice Gear Aegis Expansion">
                                <a href="/alice-gear-aegis-expansion-18373" class="film-poster-ahref item-qtip"
                                    title="Alice Gear Aegis Expansion" data-id="18373"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/alice-gear-aegis-expansion-18373"
                                        title="Alice Gear Aegis Expansion" class="dynamic-name"
                                        data-jname="Alice Gear Aegis Expansion">Alice Gear Aegis
                                        Expansion</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">20m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>4
                                    </div>


                                    <div class="tick-item tick-dub"><i class="fas fa-microphone mr-1"></i>1
                                    </div>


                                    <div class="tick-item tick-eps">12</div>

                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/0d/22/0d223280706d8f5d2f556c7951c5bf4b/0d223280706d8f5d2f556c7951c5bf4b.jpg"
                                    class="film-poster-img lazyload" alt="Kuma Kuma Kuma Bear Punch!">
                                <a href="/kuma-kuma-kuma-bear-punch-17374" class="film-poster-ahref item-qtip"
                                    title="Kuma Kuma Kuma Bear Punch!" data-id="17374"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/kuma-kuma-kuma-bear-punch-17374"
                                        title="Kuma Kuma Kuma Bear Punch!" class="dynamic-name"
                                        data-jname="Kuma Kuma Kuma Bear 2nd Season">Kuma Kuma Kuma Bear
                                        Punch!</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>3
                                    </div>


                                    <div class="tick-item tick-dub"><i class="fas fa-microphone mr-1"></i>2
                                    </div>


                                    <div class="tick-item tick-eps">12</div>

                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/bf/3c/bf3c1f30c2a3dd8ed26cd54c11992cd3/bf3c1f30c2a3dd8ed26cd54c11992cd3.jpg"
                                    class="film-poster-img lazyload"
                                    alt="The Reason Why Raeliana Ended up at the Duke's Mansion">
                                <a href="/the-reason-why-raeliana-ended-up-at-the-dukes-mansion-18350"
                                    class="film-poster-ahref item-qtip"
                                    title="The Reason Why Raeliana Ended up at the Duke's Mansion" data-id="18350"><i
                                        class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a
                                        href="/the-reason-why-raeliana-ended-up-at-the-dukes-mansion-18350"
                                        title="The Reason Why Raeliana Ended up at the Duke's Mansion"
                                        class="dynamic-name" data-jname="Kanojo ga Koushaku-tei ni Itta Riyuu">The
                                        Reason Why
                                        Raeliana Ended up at the Duke's Mansion</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">TV</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">23m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>41
                                    </div>



                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/c1/b1/c1b111d71dc055a9bd1ccc5492dfedbc/c1b111d71dc055a9bd1ccc5492dfedbc.png"
                                    class="film-poster-img lazyload" alt="Battle Through The Heavens 5th Season">
                                <a href="/battle-through-the-heavens-5th-season-18119"
                                    class="film-poster-ahref item-qtip" title="Battle Through The Heavens 5th Season"
                                    data-id="18119"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/battle-through-the-heavens-5th-season-18119"
                                        title="Battle Through The Heavens 5th Season" class="dynamic-name"
                                        data-jname="Doupo Cangqiong: Nian Fan">Battle Through The Heavens
                                        5th Season</a></h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">ONA</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">24m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="flw-item">

                            <div class="film-poster">


                                <div class="tick ltr">



                                    <div class="tick-item tick-sub"><i class="fas fa-closed-captioning mr-1"></i>33
                                    </div>



                                </div>

                                <img data-src="https://img.zorores.com/_r/300x400/100/25/e3/25e3a9b167fa92be9196d32728f6d391/25e3a9b167fa92be9196d32728f6d391.jpg"
                                    class="film-poster-img lazyload" alt="A Will Eternal">
                                <a href="/a-will-eternal-18110" class="film-poster-ahref item-qtip"
                                    title="A Will Eternal" data-id="18110"><i class="fas fa-play"></i></a>
                            </div>
                            <div class="film-detail">
                                <h3 class="film-name"><a href="/a-will-eternal-18110" title="A Will Eternal"
                                        class="dynamic-name" data-jname="Yi Nian Yong Heng: Chuan Cheng Pian">A
                                        Will Eternal</a>
                                </h3>
                                <div class="fd-infor">

                                    <span class="fdi-item">ONA</span>
                                    <span class="dot"></span>
                                    <span class="fdi-item fdi-duration">20m</span>

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>


                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </section>


    </div>



    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/shorts.js'))
        ?>

    <iframe src="about:blank" style="position: absolute; width: 1px; height: 1px; display: none; opacity: 0;"></iframe>
</body>

</html>