<?php
/**
 * 
 *  Academic/MasterController/editclassAction
 * 
 */
$this->headTitle($this->title);
 foreach($crud as $crud);
?>
<form id="#form" role="form" data-toggle="validator" action="<?php echo $this->url('reg', array('action' => 'editCrud','id'=>$crud['id'])); ?>" enctype="multipart/form-data" method="post" >
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body"> 
		<div class="panel panel-default">
			<div class="panel-body">   
				<div class="row">
					<div class="form-group col-lg-12">  
						<label class="control-label" for="name">Name</label>
						<input type="text" class="form-control" name="name" id="name" value="<?php echo $crud['name']?>" placeholder="Name"/>
					</div>
					
					<div class="form-group col-lg-12"> 
						<label class="control-label" for="description">Description</label>
						<input type="text" class="form-control" name="description" id="description" value="<?php echo $crud['description']?>" placeholder="description" /> 
					</div>
					<div class="form-group col-lg-12"> 
						<label class="control-label" for="videolink">VideoLink</label>
						<input type="text" class="form-control" name="videolink" id="videolink" value="<?php echo $crud['videolink']?>" placeholder="videolink"/> 
					</div>
					<div class="form-group col-lg-12"> 
						<label class="control-label" for="image">Image</label>
						<input type="text" class="form-control" name="image" id="image" value="<?php echo $crud['image']?>" placeholder="image" /> 
					</div>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body --> 
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>        
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			organization: {
				validators: {
					notEmpty: {
						message: 'Please provide Organization.'
					}
				}
			},
			classes: {
				validators: {
					notEmpty: {
						message: 'Please provide class.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});

});
</script>
