<?php 
/**
 * View -- of Administration/MasterController/addlocation
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('regs', array('action' => 'addstudent','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">   
				<div class="row">
					<div class="form-group col-lg-12">  
						<label class="control-label" for="name">Name</label>
						<input type="text" class="form-control" name="name" id="name" placeholder="Name"/>
					</div>
					
					<div class="form-group col-lg-12"> 
						<label class="control-label" for="cid">CID</label>
						<input type="text" class="form-control" name="cid" id="cid" placeholder="CID" /> 
					</div>
					<div class="form-group col-lg-12"> 
						<label class="control-label" for="mobile">Contact No</label>
						<input type="text" class="form-control" name="mobile" id="mobile" placeholder="Contact No" /> 
					</div>
					<div class="form-group col-lg-12"> 
						<label class="control-label" for="email">Email</label>
						<input type="text" class="form-control" name="email" id="email" placeholder="Email" /> 
					</div>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			region: {
				validators: {
					notEmpty: {
						message: 'Please select region.'
					}
				}
			},
			location_type: {
				validators: {
					notEmpty: {
						message: 'Please select location type.'
					}
				}
			},
			location: {
				validators: {
					notEmpty: {
						message: 'Please provide location name.'
					}
				}
			},
			district: {
				validators: {
					notEmpty: {
						message: 'Please select dzongkhag.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>