<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Athang Studio')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/lo3.png',
    ])
        // ->prependStylesheet($this->basePath('css/all.css'))
        ->prependStylesheet($this->basePath('css/animate.compat.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))
        // ->prependStylesheet($this->basePath('css/bootstrap-icons.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.css'))
        // ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/media.css'))
        ->prependStylesheet($this->basePath('css/nullstyle.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        // ->prependStylesheet($this->basePath('css/styles.min.css'))
        ->prependStylesheet($this->basePath('css/yeshi.css'))
        ->prependStylesheet($this->basePath('css/style.scss'))
    ?>

    <?= $this->headLink([
        'rel' => 'stylesheet',
        'href' => 'https://fonts.googleapis.com/icon?family=Material+Icons',
    ]) ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>


<body>
    <!-- navbar -->
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <a href="https://www.athang.com/public/w" class="header__logo logo">
                    <img src="img/Athang_logo.jpg" alt="logo" class="logo__img img">
                    <span>Athang Studio</span>
                </a>
                <div class="header__body">
                    <nav class="menu">
                        <ul class="menu__list">
                            <li class="menu__item">
                                <a href="/" class="menu__link">Home</a>
                            </li>
                            <li class="menu__item">
                                <a href="/ap" class="menu__link">Ap Bokto</a>
                            </li>
                            <li class="menu__item">
                                <a href="/shorts" class="menu__link"> Shorts</a>
                            </li>
                            <li class="menu__item">
                                <a href="/services" class="menu__link">Studio</a>
                            </li>
                            <li class="menu__item">
                                <a href="/contact" class="menu__link">Contact Us</a>
                            </li>

                            <li class="menu__item">
                                <a href="/about" class="menu__link">About Us</a>
                            </li>


                        </ul>
                    </nav>


                    <div class="header__burger">
                        <span></span>
                    </div>
                </div>
            </div>
    </header>

    <!-- <div class="container"> -->
        <?= $this->content ?>
        <hr>
        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="footer__inner">
                    <div class="footer__block">
                        <a href="https://www.athang.com/public/w" class="footer__logo logo">
                            <img src="img/Athang_logo.jpg" alt="logo" class="logo__img img">
                            <span>Athang Studio</span>
                        </a>

                        <p class="footer-contact__item text1" style="color:#707070;">Athang believes in the
                            team
                            work and democratic working
                            culture to bring the best of every employees at personal as well as professional
                            level. As credentials, Athang has been with some international
                            organizations in IT/software Services, professional training,
                            and 3D animations.</p>
                        <br>


                        <div class="footer__text text1">
                            Do follow us on
                        </div>
                        <div class="footer__socials">
                            <a href="https://www.facebook.com/profile.php?id=100057108984264" class="footer__social">
                                <img src="img/fb.svg" alt="footer img" class="footer__img img">
                            </a>
                            <a href="https://www.instagram.com/athang215/" class="footer__social">
                                <img src="img/in.svg" alt="footer img" class="footer__img img">
                            </a>
                            <a href="https://twitter.com/home" class="footer__social">
                                <img src="img/tw.svg" alt="footer img" class="footer__img img">
                            </a>
                        </div>
                    </div>
                    <div class="footer__block footer-contact">
                        <div class="footer-contact__header">Contact Us</div>
                        <ul class="footer-contact__list">
                            <li class="footer-contact__item text1">
                                <a href="tel:+123456789123" class="footer-contact__link">Phone: +975 02
                                    333849/333655</a>
                            </li>
                            <li class="footer-contact__item text1">
                                <a href="tel:+123456789123" class="footer-contact__link">Mobile: +975
                                    17110989/17115890</a>
                            </li>
                            <li class="footer-contact__item text1">
                                <a href="mailto:info@athang.com,karma@athang.com" class="footer-contact__link">Email:
                                    info@athang.com / karma@athang.com</a>
                            </li>

                            <li class="footer-contact__item text1">
                                <a href="https://www.google.com/maps/place/Athang+Learning+Institute/@27.4712215,89.6290332,17z/data=!3m1!4b1!4m11!1m3!11m2!2shsCfYudIceHKNGF2RMSX9M272f76FA!3e1!3m6!1s0x39e1958b0fdbbf2f:0x6ad2ba8a60502b3e!8m2!3d27.4712216!4d89.6339041!15sCgEqkgEPdHJhaW5pbmdfc2Nob29s4AEA!16s%2Fg%2F11fq0r_qdk"
                                    class="footer-contact__link" target="_blank">Babena, Below Dechen Phodrang
                                    Monastery.</a>
                            </li>
                                     </ul>
                    </div>
                    <div class="footer__block footer-link">
                        <div class="footer-link__header">Explore</div>
                        <ul class="footer-link__list">
                            <li class="footer-link__item text1">
                                <a href="#" class="footer-link__link">About Us</a>
                            </li>
                            <li class="footer-link__item text1">
                                <a href="/adver" class="footer-link__link">Ap Bokto Series</a>
                            </li>

                            <li class="footer-link__item text1">
                                <a href="/video" class="footer-link__link">Shorts</a>
                            </li>
                            <li class="footer-link__item text1">
                                <a href="/contact" class="footer-link__link">Contact Us</a>
                            </li>

                        </ul>
                    </div>
                    <div class="footer__block footer-link">
                        <div class="footer-link__header">Useful links</div>
                        <ul class="footer-link__list">
                            <li class="footer-link__item text1">
                                <a href="https://www.athang.com/public/w/aboutus" class="footer-link__link">About
                                    Athang</a>
                            </li>
                            <li class="footer-link__item text1">
                                <a href="https://www.athang.com/public/ppage" class="footer-link__link">News &
                                    Announcements</a>
                            </li>
                            <li class="footer-link__item text1">
                                <a href="#" class="footer-link__link"></a>
                            </li>
                            <li class="footer-link__item text1">
                                <a href="#" class="footer-link__link"></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="footer__copyright">
                    <div class="footer__cooper text1">Copyright ©
                        <a href="https://github.com/Tharchen03/Athang_studio" class="footer__link-bio"
                            target="_blank">Athang_Studio</a>, 2023.
                        All rights reserved.
                    </div>
                </div>
            </div>
        </footer>
       
    <!-- </div> -->

  
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/about.js'))
        ->prependFile($this->basePath('js/app.min.js'))
        ->prependFile($this->basePath('js/script.js'))
        ->prependFile($this->basePath('js/slick.min.js'))
        ->prependFile($this->basePath('js/socket.io.min.js'))
        ->prependFile($this->basePath('js/tag.min.js'))
        ->prependFile($this->basePath('js/yeshi.js'))
         ?>
</body>

</html>